### ISSUE TITLE
feature: expose execution state to user

### ISSUE THREAD

**Issue by skyzh** [singularity-data/sqllogictest-rs#3]
Currently, if a tester fails, we cannot know which test fails in console -- users will need to manually `export RUST_LOG=info` to see the result.

We should have some interface to let user know which statement is being executed. I propose a interface like:

```rust
for next_statement in tester.run_script(&script) {
   println!("running {:?}", next_statement);
}
```

When `next` is called on iterator, `next_statement` will be running in sqllogictest internally.

We can also go a step further to expose all our internal states:

```rust
for (statement, verifier) in tester.parse_script(&script) {
   let result = db.run(statement).await;
   verifier.verify(result.to_string()).unwrap();
}
```

**Comment by wangrunji0408** [comment]
The `run_script` function is designed to be a quick way to parse and run script in 1 line.

If you care about each statement, you can use more fine-grained API such as:
```rust
for record in parse(&script).unwrap() {
    println!("running {:?}", record);
    tester.run(record);
}
```

What we can do next is to return an error if a statement fails, rather than panicking inside now.
