### ISSUE TITLE
RFC: Supporting `include` statement.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/sqllogictest-rs#5]
# Motivation

When writing tests for complex queries, we need to prepare data before executing queries. The most general approach is to execute `insert into` statements. However, mixing a lot of insert statements with queries in one file may lead to a large file which is difficult to maintain and understand.

# Proposal

A good practice is to split these statements into small files and use `include` statements to merge them together. For example, tpch e2e tests may  consist of several files: one file for creating tables, one file for each table's data, and one file for all queries, and eventually we use `include` command to concat them together.

```
include "create.slt"
include "insert_nation.slt"
include "insert_lineitem.slt"

query R
select * from lineitem;
```

**Comment by TennyZhuang** [comment]
This is not a feature of original sqllogtest, but it’s really useful, so +1 for this.

I prefer to use “source” instead of “include”.

**Comment by skyzh** [comment]
Resolved in https://github.com/singularity-data/sqllogictest-rs/pull/8
